"""Export centralisé de tous les modèles SQLAlchemy."""
from app.models.absence_discipline import Absence, IncidentDisciplinaire
from app.models.audit import JournalAudit
from app.models.document import DocumentAdministratif
from app.models.eleve import Eleve, EleveParent, Inscription, ParentTuteur
from app.models.emploi_temps import (
    AffectationEnseignant,
    CreneauEmploiTemps,
    Enseignant,
    Salle,
)
from app.models.etablissement import (
    PROGRAM_CODE_GENERAL,
    PROGRAM_NAME_GENERAL,
    AcademicPeriod,
    AnneeScolaire,
    Classe,
    Etablissement,
    EvenementCalendrier,
    NiveauEtude,
    Program,
    Trimestre,
)
from app.models.finance import (
    EcheancePaiement,
    FraisScolaire,
    Paiement,
    seq_numero_recu,
)
from app.models.grading import (
    AUDIT_GRADING_RULE_COMPONENT_CREATED,
    AUDIT_GRADING_RULE_COMPONENT_DELETED,
    AUDIT_GRADING_RULE_COMPONENT_UPDATED,
    AUDIT_GRADING_RULESET_ACTIVATED,
    AUDIT_GRADING_RULESET_ARCHIVED,
    AUDIT_GRADING_RULESET_CREATED,
    AUDIT_GRADING_RULESET_UPDATED,
    DEFAULT_SCALE_MAX,
    EVALUATION_CONTEXTS,
    GRADING_ROUNDING_MODES,
    GRADING_RULESET_STATUSES,
    SYSTEM_EVALUATION_TYPE_CODES,
    WEIGHT_PERCENT_SCALE,
    EvaluationType,
    GradingRuleComponent,
    GradingRuleset,
)
from app.models.notification import Notification
from app.models.pedagogie import (
    Bulletin,
    CoefficientMatiere,
    Evaluation,
    Matiere,
    Note,
    ProgrammeDevoir,
    SeanceCours,
)
from app.models.school import School
from app.models.utilisateur import (
    PLATFORM_ROLE_SUPER_ADMIN,
    PLATFORM_ROLES,
    ROLES,
    SCHOOL_ROLES,
    RefreshToken,
    ReinitialisationMdp,
    Utilisateur,
)

__all__ = [
    "AUDIT_GRADING_RULESET_ACTIVATED",
    "AUDIT_GRADING_RULESET_ARCHIVED",
    "AUDIT_GRADING_RULESET_CREATED",
    "AUDIT_GRADING_RULESET_UPDATED",
    "AUDIT_GRADING_RULE_COMPONENT_CREATED",
    "AUDIT_GRADING_RULE_COMPONENT_DELETED",
    "AUDIT_GRADING_RULE_COMPONENT_UPDATED",
    "DEFAULT_SCALE_MAX",
    "EVALUATION_CONTEXTS",
    "GRADING_ROUNDING_MODES",
    "GRADING_RULESET_STATUSES",
    "PLATFORM_ROLES",
    "PLATFORM_ROLE_SUPER_ADMIN",
    "PROGRAM_CODE_GENERAL",
    "PROGRAM_NAME_GENERAL",
    "ROLES",
    "SCHOOL_ROLES",
    "SYSTEM_EVALUATION_TYPE_CODES",
    "WEIGHT_PERCENT_SCALE",
    "Absence",
    "AcademicPeriod",
    "AffectationEnseignant",
    "AnneeScolaire",
    "Bulletin",
    "Classe",
    "CoefficientMatiere",
    "CreneauEmploiTemps",
    "DocumentAdministratif",
    "EcheancePaiement",
    "Eleve",
    "EleveParent",
    "Enseignant",
    "Etablissement",
    "Evaluation",
    "EvaluationType",
    "EvenementCalendrier",
    "FraisScolaire",
    "GradingRuleComponent",
    "GradingRuleset",
    "IncidentDisciplinaire",
    "Inscription",
    "JournalAudit",
    "Matiere",
    "NiveauEtude",
    "Note",
    "Notification",
    "Paiement",
    "ParentTuteur",
    "Program",
    "ProgrammeDevoir",
    "RefreshToken",
    "ReinitialisationMdp",
    "Salle",
    "School",
    "SeanceCours",
    "Trimestre",
    "Utilisateur",
    "seq_numero_recu",
]
