import {
  Bell,
  BookOpen,
  Building2,
  Calendar,
  ClipboardList,
  FileText,
  FolderOpen,
  GraduationCap,
  History,
  Layers,
  NotebookPen,
  Receipt,
  Scale,
  ScrollText,
  ShieldAlert,
  UserCog,
  Users,
  Wallet,
} from 'lucide-react';

/** Icônes standard pour les états vides des tableaux */
export const emptyIcons = {
  absences: ClipboardList,
  affectations: UserCog,
  annees: Calendar,
  arrieres: Wallet,
  audit: History,
  bulletins: ScrollText,
  calendrier: Calendar,
  classes: GraduationCap,
  coefficients: Scale,
  compositions: FileText,
  devoirs: BookOpen,
  discipline: ShieldAlert,
  documents: FolderOpen,
  eleves: GraduationCap,
  enseignants: Users,
  evaluations: FileText,
  finance: Wallet,
  matieres: BookOpen,
  niveaux: Layers,
  notifications: Bell,
  paiements: Receipt,
  salles: Building2,
  seances: NotebookPen,
  trimestres: Calendar,
  utilisateurs: Users,
};
